name: Deploy to Production

on:
  push:
    branches:
      - deploy/prod

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*.jar

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/libs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 애플리케이션 중지
            sudo systemctl stop hangeul-hunters || true
            
            # 기존 JAR 파일 백업 및 새 JAR 파일 복사
            mkdir -p ~/backup
            cp ~/app/hangeul-hunters.jar ~/backup/hangeul-hunters-$(date +%Y%m%d%H%M%S).jar || true
            
            # 새 JAR 파일 복사
            cp build/libs/*.jar ~/app/hangeul-hunters.jar
            
            # 환경 변수 설정
            sudo tee /etc/systemd/system/hangeul-hunters.service > /dev/null << EOT
            [Unit]
            Description=Hangeul Hunters Application
            After=network.target
            
            [Service]
            Type=simple
            User=${{ secrets.EC2_USERNAME }}
            WorkingDirectory=/home/${{ secrets.EC2_USERNAME }}/app
            ExecStart=/usr/bin/java -jar hangeul-hunters.jar --spring.profiles.active=prod
            Environment="DATABASE_URL=${{ secrets.DATABASE_URL }}"
            Environment="DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}"
            Environment="DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}"
            # EC2 인스턴스 IAM 역할 사용
            Environment="AWS_REGION=ap-northeast-2"
            Environment="AWS_BUCKET_NAME=noonchi-bucket"
            Environment="JWT_SECRET=${{ secrets.JWT_SECRET }}"
            Restart=always
            
            [Install]
            WantedBy=multi-user.target
            EOT
            
            # 서비스 리로드 및 시작
            sudo systemctl daemon-reload
            sudo systemctl enable hangeul-hunters
            sudo systemctl start hangeul-hunters
            
            # 서비스 상태 확인
            sudo systemctl status hangeul-hunters